import { Main } from "next/document";
import Head from "next/head";

export default function Home() {
  return (
    <>
    <Head>
      <title>Belajar Next.js</title>
      <meta name="description" content="Generated by learn next.js" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <div className="h-screen flex items-center justify-center font-bold text-2xl md:text-4xl">
            <h1 className="mx-4 text-center">Ini adalah halaman Utama.</h1>
        </div>
    </main>
    </>
  );
}
