import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hisbil Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="flex justify-center items-center w-100 p-3"
          style={{ height: "50px", background: "orange" }}
        >
          <ul className="flex">
            <li className="bg-white rounded p-2">
              <Link href="/">Home</Link>
            </li>
            <li className="bg-white rounded p-2 ml-2">
              <Link href="/about">About</Link>
            </li>
          </ul>
        </div>
        <div>
          <h1 className="text-3xl text-center"> Home pages</h1>
        </div>
      </main>
    </>
  );
}
